//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class alumni_admin
    {
        [DisplayName("Admin ID")]
        public int adm_id { get; set; }
        [DisplayName("Admin GUID")]
        public Nullable<System.Guid> adm_guid { get; set; }
        [DisplayName("Admin Name")]
        [Required]
        public string adm_name { get; set; }
        [DisplayName("Admin Email")]
        [Required]
        public string adm_email { get; set; }
        [DisplayName("Admin Password")]
        [Required]
        public string adm_password { get; set; }
        [DisplayName("Admin is_active")]
        [Required]
        public Nullable<bool> is_active { get; set; }
        [DisplayName("Campus")]
        [Required]
        public string campus { get; set; }
        [DisplayName("Created At")]
        public Nullable<System.DateTime> created_at { get; set; }
        [DisplayName("Created By")]
        public string created_by { get; set; }
        [DisplayName("Updated At")]
        public Nullable<System.DateTime> updated_at { get; set; }
        [DisplayName("Updated By")]
        public string updated_by { get; set; }
    }
}
