//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public candidate()
        {
            this.member_candidate = new HashSet<member_candidate>();
        }
    
        public string election_title { get; set; }
        public string category_name { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public string grad_dept { get; set; }
        public string grad_year { get; set; }
        public string indust_org_working { get; set; }
        public string exper_years { get; set; }
        public string town_city_province { get; set; }
        public string message_to_voter { get; set; }
        public string education { get; set; }
        public string experience_details { get; set; }
        public int candidate_id { get; set; }
    
        public virtual category category { get; set; }
        public virtual election election { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<member_candidate> member_candidate { get; set; }
    }
}
