//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class FUI_POLLEntities : DbContext
    {
        public FUI_POLLEntities()
            : base("name=FUI_POLLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<candidate> candidates { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<election> elections { get; set; }
        public virtual DbSet<validation_status> validation_status { get; set; }
        public virtual DbSet<member_candidate> member_candidate { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<alumni_admin> alumni_admin { get; set; }
        public virtual DbSet<job_post> job_post { get; set; }
        public virtual DbSet<upcoming_event> upcoming_event { get; set; }
        public virtual DbSet<news> news { get; set; }
    
        public virtual ObjectResult<get_polls_sp_Result> get_polls_sp(Nullable<System.Guid> guid)
        {
            var guidParameter = guid.HasValue ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_polls_sp_Result>("get_polls_sp", guidParameter);
        }
    
        public virtual ObjectResult<get_presidents_sp_Result> get_presidents_sp()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<get_presidents_sp_Result>("get_presidents_sp");
        }
    
        public virtual int insert_nomination_sp(string position, string name, string father_name, string reg_number, string grad_year, string grad_dept, string indust_org, string experi_years, string email, string mobile_num, string cnic, string town_city_provice, string cv_path, string image)
        {
            var positionParameter = position != null ?
                new ObjectParameter("position", position) :
                new ObjectParameter("position", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var father_nameParameter = father_name != null ?
                new ObjectParameter("father_name", father_name) :
                new ObjectParameter("father_name", typeof(string));
    
            var reg_numberParameter = reg_number != null ?
                new ObjectParameter("reg_number", reg_number) :
                new ObjectParameter("reg_number", typeof(string));
    
            var grad_yearParameter = grad_year != null ?
                new ObjectParameter("grad_year", grad_year) :
                new ObjectParameter("grad_year", typeof(string));
    
            var grad_deptParameter = grad_dept != null ?
                new ObjectParameter("grad_dept", grad_dept) :
                new ObjectParameter("grad_dept", typeof(string));
    
            var indust_orgParameter = indust_org != null ?
                new ObjectParameter("indust_org", indust_org) :
                new ObjectParameter("indust_org", typeof(string));
    
            var experi_yearsParameter = experi_years != null ?
                new ObjectParameter("experi_years", experi_years) :
                new ObjectParameter("experi_years", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var mobile_numParameter = mobile_num != null ?
                new ObjectParameter("mobile_num", mobile_num) :
                new ObjectParameter("mobile_num", typeof(string));
    
            var cnicParameter = cnic != null ?
                new ObjectParameter("cnic", cnic) :
                new ObjectParameter("cnic", typeof(string));
    
            var town_city_proviceParameter = town_city_provice != null ?
                new ObjectParameter("town_city_provice", town_city_provice) :
                new ObjectParameter("town_city_provice", typeof(string));
    
            var cv_pathParameter = cv_path != null ?
                new ObjectParameter("cv_path", cv_path) :
                new ObjectParameter("cv_path", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("image", image) :
                new ObjectParameter("image", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_nomination_sp", positionParameter, nameParameter, father_nameParameter, reg_numberParameter, grad_yearParameter, grad_deptParameter, indust_orgParameter, experi_yearsParameter, emailParameter, mobile_numParameter, cnicParameter, town_city_proviceParameter, cv_pathParameter, imageParameter);
        }
    
        public virtual int insert_poll_sp(Nullable<int> president_id, Nullable<int> vicepresident_id, string email, Nullable<System.Guid> guid, string ip_address)
        {
            var president_idParameter = president_id.HasValue ?
                new ObjectParameter("president_id", president_id) :
                new ObjectParameter("president_id", typeof(int));
    
            var vicepresident_idParameter = vicepresident_id.HasValue ?
                new ObjectParameter("vicepresident_id", vicepresident_id) :
                new ObjectParameter("vicepresident_id", typeof(int));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var guidParameter = guid.HasValue ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(System.Guid));
    
            var ip_addressParameter = ip_address != null ?
                new ObjectParameter("ip_address", ip_address) :
                new ObjectParameter("ip_address", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_poll_sp", president_idParameter, vicepresident_idParameter, emailParameter, guidParameter, ip_addressParameter);
        }
    
        public virtual int update_poll_sp(string president_id, string vicepresident_id, string secretary_id, string treasurer_id, Nullable<System.Guid> guid, string ip_address, string headers)
        {
            var president_idParameter = president_id != null ?
                new ObjectParameter("president_id", president_id) :
                new ObjectParameter("president_id", typeof(string));
    
            var vicepresident_idParameter = vicepresident_id != null ?
                new ObjectParameter("vicepresident_id", vicepresident_id) :
                new ObjectParameter("vicepresident_id", typeof(string));
    
            var secretary_idParameter = secretary_id != null ?
                new ObjectParameter("secretary_id", secretary_id) :
                new ObjectParameter("secretary_id", typeof(string));
    
            var treasurer_idParameter = treasurer_id != null ?
                new ObjectParameter("treasurer_id", treasurer_id) :
                new ObjectParameter("treasurer_id", typeof(string));
    
            var guidParameter = guid.HasValue ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(System.Guid));
    
            var ip_addressParameter = ip_address != null ?
                new ObjectParameter("ip_address", ip_address) :
                new ObjectParameter("ip_address", typeof(string));
    
            var headersParameter = headers != null ?
                new ObjectParameter("headers", headers) :
                new ObjectParameter("headers", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_poll_sp", president_idParameter, vicepresident_idParameter, secretary_idParameter, treasurer_idParameter, guidParameter, ip_addressParameter, headersParameter);
        }
    
        public virtual int get_members_sp(Nullable<System.Guid> guid)
        {
            var guidParameter = guid.HasValue ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("get_members_sp", guidParameter);
        }
    
        public virtual int update_member_candidate_sp(Nullable<System.Guid> guid, Nullable<int> candidate_id, string ip_address, string headers)
        {
            var guidParameter = guid.HasValue ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(System.Guid));
    
            var candidate_idParameter = candidate_id.HasValue ?
                new ObjectParameter("candidate_id", candidate_id) :
                new ObjectParameter("candidate_id", typeof(int));
    
            var ip_addressParameter = ip_address != null ?
                new ObjectParameter("ip_address", ip_address) :
                new ObjectParameter("ip_address", typeof(string));
    
            var headersParameter = headers != null ?
                new ObjectParameter("headers", headers) :
                new ObjectParameter("headers", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_member_candidate_sp", guidParameter, candidate_idParameter, ip_addressParameter, headersParameter);
        }
    
        public virtual int insert_nomination_sp1(string position, string name, string father_name, string reg_number, string grad_year, string grad_dept, string indust_org, string experi_years, string email, string mobile_num, string cnic, string town_city_provice, string cv_path, string image)
        {
            var positionParameter = position != null ?
                new ObjectParameter("position", position) :
                new ObjectParameter("position", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var father_nameParameter = father_name != null ?
                new ObjectParameter("father_name", father_name) :
                new ObjectParameter("father_name", typeof(string));
    
            var reg_numberParameter = reg_number != null ?
                new ObjectParameter("reg_number", reg_number) :
                new ObjectParameter("reg_number", typeof(string));
    
            var grad_yearParameter = grad_year != null ?
                new ObjectParameter("grad_year", grad_year) :
                new ObjectParameter("grad_year", typeof(string));
    
            var grad_deptParameter = grad_dept != null ?
                new ObjectParameter("grad_dept", grad_dept) :
                new ObjectParameter("grad_dept", typeof(string));
    
            var indust_orgParameter = indust_org != null ?
                new ObjectParameter("indust_org", indust_org) :
                new ObjectParameter("indust_org", typeof(string));
    
            var experi_yearsParameter = experi_years != null ?
                new ObjectParameter("experi_years", experi_years) :
                new ObjectParameter("experi_years", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var mobile_numParameter = mobile_num != null ?
                new ObjectParameter("mobile_num", mobile_num) :
                new ObjectParameter("mobile_num", typeof(string));
    
            var cnicParameter = cnic != null ?
                new ObjectParameter("cnic", cnic) :
                new ObjectParameter("cnic", typeof(string));
    
            var town_city_proviceParameter = town_city_provice != null ?
                new ObjectParameter("town_city_provice", town_city_provice) :
                new ObjectParameter("town_city_provice", typeof(string));
    
            var cv_pathParameter = cv_path != null ?
                new ObjectParameter("cv_path", cv_path) :
                new ObjectParameter("cv_path", typeof(string));
    
            var imageParameter = image != null ?
                new ObjectParameter("image", image) :
                new ObjectParameter("image", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_nomination_sp1", positionParameter, nameParameter, father_nameParameter, reg_numberParameter, grad_yearParameter, grad_deptParameter, indust_orgParameter, experi_yearsParameter, emailParameter, mobile_numParameter, cnicParameter, town_city_proviceParameter, cv_pathParameter, imageParameter);
        }
    
        public virtual int insert_member_sp(string name, string email, Nullable<System.Guid> guid, string mobile_no, string ip_address, string headers, Nullable<System.DateTime> created_at, string created_by, Nullable<bool> already_voted, string password, string confirm_password, string registration_no, Nullable<System.DateTime> degree_completion_date, string campus, string category_studied, string program_studied, string org_comp_working_in, string designation)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var guidParameter = guid.HasValue ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(System.Guid));
    
            var mobile_noParameter = mobile_no != null ?
                new ObjectParameter("mobile_no", mobile_no) :
                new ObjectParameter("mobile_no", typeof(string));
    
            var ip_addressParameter = ip_address != null ?
                new ObjectParameter("ip_address", ip_address) :
                new ObjectParameter("ip_address", typeof(string));
    
            var headersParameter = headers != null ?
                new ObjectParameter("headers", headers) :
                new ObjectParameter("headers", typeof(string));
    
            var created_atParameter = created_at.HasValue ?
                new ObjectParameter("created_at", created_at) :
                new ObjectParameter("created_at", typeof(System.DateTime));
    
            var created_byParameter = created_by != null ?
                new ObjectParameter("created_by", created_by) :
                new ObjectParameter("created_by", typeof(string));
    
            var already_votedParameter = already_voted.HasValue ?
                new ObjectParameter("already_voted", already_voted) :
                new ObjectParameter("already_voted", typeof(bool));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var confirm_passwordParameter = confirm_password != null ?
                new ObjectParameter("confirm_password", confirm_password) :
                new ObjectParameter("confirm_password", typeof(string));
    
            var registration_noParameter = registration_no != null ?
                new ObjectParameter("registration_no", registration_no) :
                new ObjectParameter("registration_no", typeof(string));
    
            var degree_completion_dateParameter = degree_completion_date.HasValue ?
                new ObjectParameter("degree_completion_date", degree_completion_date) :
                new ObjectParameter("degree_completion_date", typeof(System.DateTime));
    
            var campusParameter = campus != null ?
                new ObjectParameter("campus", campus) :
                new ObjectParameter("campus", typeof(string));
    
            var category_studiedParameter = category_studied != null ?
                new ObjectParameter("category_studied", category_studied) :
                new ObjectParameter("category_studied", typeof(string));
    
            var program_studiedParameter = program_studied != null ?
                new ObjectParameter("program_studied", program_studied) :
                new ObjectParameter("program_studied", typeof(string));
    
            var org_comp_working_inParameter = org_comp_working_in != null ?
                new ObjectParameter("org_comp_working_in", org_comp_working_in) :
                new ObjectParameter("org_comp_working_in", typeof(string));
    
            var designationParameter = designation != null ?
                new ObjectParameter("designation", designation) :
                new ObjectParameter("designation", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_member_sp", nameParameter, emailParameter, guidParameter, mobile_noParameter, ip_addressParameter, headersParameter, created_atParameter, created_byParameter, already_votedParameter, passwordParameter, confirm_passwordParameter, registration_noParameter, degree_completion_dateParameter, campusParameter, category_studiedParameter, program_studiedParameter, org_comp_working_inParameter, designationParameter);
        }
    
        public virtual int update_member_sp(Nullable<int> member_id, string name, string email, Nullable<System.Guid> guid, string mobile_no, string ip_address, string headers, Nullable<System.DateTime> created_at, string created_by, Nullable<System.DateTime> updated_at, string updated_by, Nullable<bool> already_voted, string password, string confirm_password, string registration_no, Nullable<System.DateTime> degree_completion_date, string campus, string category_studied, string program_studied, string org_comp_working_in, string designation, Nullable<int> validation_status)
        {
            var member_idParameter = member_id.HasValue ?
                new ObjectParameter("member_id", member_id) :
                new ObjectParameter("member_id", typeof(int));
    
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            var guidParameter = guid.HasValue ?
                new ObjectParameter("guid", guid) :
                new ObjectParameter("guid", typeof(System.Guid));
    
            var mobile_noParameter = mobile_no != null ?
                new ObjectParameter("mobile_no", mobile_no) :
                new ObjectParameter("mobile_no", typeof(string));
    
            var ip_addressParameter = ip_address != null ?
                new ObjectParameter("ip_address", ip_address) :
                new ObjectParameter("ip_address", typeof(string));
    
            var headersParameter = headers != null ?
                new ObjectParameter("headers", headers) :
                new ObjectParameter("headers", typeof(string));
    
            var created_atParameter = created_at.HasValue ?
                new ObjectParameter("created_at", created_at) :
                new ObjectParameter("created_at", typeof(System.DateTime));
    
            var created_byParameter = created_by != null ?
                new ObjectParameter("created_by", created_by) :
                new ObjectParameter("created_by", typeof(string));
    
            var updated_atParameter = updated_at.HasValue ?
                new ObjectParameter("updated_at", updated_at) :
                new ObjectParameter("updated_at", typeof(System.DateTime));
    
            var updated_byParameter = updated_by != null ?
                new ObjectParameter("updated_by", updated_by) :
                new ObjectParameter("updated_by", typeof(string));
    
            var already_votedParameter = already_voted.HasValue ?
                new ObjectParameter("already_voted", already_voted) :
                new ObjectParameter("already_voted", typeof(bool));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var confirm_passwordParameter = confirm_password != null ?
                new ObjectParameter("confirm_password", confirm_password) :
                new ObjectParameter("confirm_password", typeof(string));
    
            var registration_noParameter = registration_no != null ?
                new ObjectParameter("registration_no", registration_no) :
                new ObjectParameter("registration_no", typeof(string));
    
            var degree_completion_dateParameter = degree_completion_date.HasValue ?
                new ObjectParameter("degree_completion_date", degree_completion_date) :
                new ObjectParameter("degree_completion_date", typeof(System.DateTime));
    
            var campusParameter = campus != null ?
                new ObjectParameter("campus", campus) :
                new ObjectParameter("campus", typeof(string));
    
            var category_studiedParameter = category_studied != null ?
                new ObjectParameter("category_studied", category_studied) :
                new ObjectParameter("category_studied", typeof(string));
    
            var program_studiedParameter = program_studied != null ?
                new ObjectParameter("program_studied", program_studied) :
                new ObjectParameter("program_studied", typeof(string));
    
            var org_comp_working_inParameter = org_comp_working_in != null ?
                new ObjectParameter("org_comp_working_in", org_comp_working_in) :
                new ObjectParameter("org_comp_working_in", typeof(string));
    
            var designationParameter = designation != null ?
                new ObjectParameter("designation", designation) :
                new ObjectParameter("designation", typeof(string));
    
            var validation_statusParameter = validation_status.HasValue ?
                new ObjectParameter("validation_status", validation_status) :
                new ObjectParameter("validation_status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_member_sp", member_idParameter, nameParameter, emailParameter, guidParameter, mobile_noParameter, ip_addressParameter, headersParameter, created_atParameter, created_byParameter, updated_atParameter, updated_byParameter, already_votedParameter, passwordParameter, confirm_passwordParameter, registration_noParameter, degree_completion_dateParameter, campusParameter, category_studiedParameter, program_studiedParameter, org_comp_working_inParameter, designationParameter, validation_statusParameter);
        }
    
        public virtual int insert_job_post(string title, string category, string post_type, string location, string description, string salary, string tags, string image_path, string campus, Nullable<System.DateTime> created_at, string created_by)
        {
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var post_typeParameter = post_type != null ?
                new ObjectParameter("post_type", post_type) :
                new ObjectParameter("post_type", typeof(string));
    
            var locationParameter = location != null ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var salaryParameter = salary != null ?
                new ObjectParameter("salary", salary) :
                new ObjectParameter("salary", typeof(string));
    
            var tagsParameter = tags != null ?
                new ObjectParameter("tags", tags) :
                new ObjectParameter("tags", typeof(string));
    
            var image_pathParameter = image_path != null ?
                new ObjectParameter("image_path", image_path) :
                new ObjectParameter("image_path", typeof(string));
    
            var campusParameter = campus != null ?
                new ObjectParameter("campus", campus) :
                new ObjectParameter("campus", typeof(string));
    
            var created_atParameter = created_at.HasValue ?
                new ObjectParameter("created_at", created_at) :
                new ObjectParameter("created_at", typeof(System.DateTime));
    
            var created_byParameter = created_by != null ?
                new ObjectParameter("created_by", created_by) :
                new ObjectParameter("created_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_job_post", titleParameter, categoryParameter, post_typeParameter, locationParameter, descriptionParameter, salaryParameter, tagsParameter, image_pathParameter, campusParameter, created_atParameter, created_byParameter);
        }
    
        public virtual int update_job_post(Nullable<int> job_post_id, string title, string category, string post_type, string location, string description, string salary, string tags, string image_path, string campus, Nullable<System.DateTime> created_at, string created_by, Nullable<System.DateTime> updated_at, string updated_by)
        {
            var job_post_idParameter = job_post_id.HasValue ?
                new ObjectParameter("job_post_id", job_post_id) :
                new ObjectParameter("job_post_id", typeof(int));
    
            var titleParameter = title != null ?
                new ObjectParameter("title", title) :
                new ObjectParameter("title", typeof(string));
    
            var categoryParameter = category != null ?
                new ObjectParameter("category", category) :
                new ObjectParameter("category", typeof(string));
    
            var post_typeParameter = post_type != null ?
                new ObjectParameter("post_type", post_type) :
                new ObjectParameter("post_type", typeof(string));
    
            var locationParameter = location != null ?
                new ObjectParameter("location", location) :
                new ObjectParameter("location", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("description", description) :
                new ObjectParameter("description", typeof(string));
    
            var salaryParameter = salary != null ?
                new ObjectParameter("salary", salary) :
                new ObjectParameter("salary", typeof(string));
    
            var tagsParameter = tags != null ?
                new ObjectParameter("tags", tags) :
                new ObjectParameter("tags", typeof(string));
    
            var image_pathParameter = image_path != null ?
                new ObjectParameter("image_path", image_path) :
                new ObjectParameter("image_path", typeof(string));
    
            var campusParameter = campus != null ?
                new ObjectParameter("campus", campus) :
                new ObjectParameter("campus", typeof(string));
    
            var created_atParameter = created_at.HasValue ?
                new ObjectParameter("created_at", created_at) :
                new ObjectParameter("created_at", typeof(System.DateTime));
    
            var created_byParameter = created_by != null ?
                new ObjectParameter("created_by", created_by) :
                new ObjectParameter("created_by", typeof(string));
    
            var updated_atParameter = updated_at.HasValue ?
                new ObjectParameter("updated_at", updated_at) :
                new ObjectParameter("updated_at", typeof(System.DateTime));
    
            var updated_byParameter = updated_by != null ?
                new ObjectParameter("updated_by", updated_by) :
                new ObjectParameter("updated_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_job_post", job_post_idParameter, titleParameter, categoryParameter, post_typeParameter, locationParameter, descriptionParameter, salaryParameter, tagsParameter, image_pathParameter, campusParameter, created_atParameter, created_byParameter, updated_atParameter, updated_byParameter);
        }
    
        public virtual int insert_upcoming_event(Nullable<System.Guid> event_guid, Nullable<System.DateTime> event_date_time, string event_title, string event_details, string campus, string event_link, Nullable<System.DateTime> event_expir_date, Nullable<System.DateTime> created_at, string created_by)
        {
            var event_guidParameter = event_guid.HasValue ?
                new ObjectParameter("event_guid", event_guid) :
                new ObjectParameter("event_guid", typeof(System.Guid));
    
            var event_date_timeParameter = event_date_time.HasValue ?
                new ObjectParameter("event_date_time", event_date_time) :
                new ObjectParameter("event_date_time", typeof(System.DateTime));
    
            var event_titleParameter = event_title != null ?
                new ObjectParameter("event_title", event_title) :
                new ObjectParameter("event_title", typeof(string));
    
            var event_detailsParameter = event_details != null ?
                new ObjectParameter("event_details", event_details) :
                new ObjectParameter("event_details", typeof(string));
    
            var campusParameter = campus != null ?
                new ObjectParameter("campus", campus) :
                new ObjectParameter("campus", typeof(string));
    
            var event_linkParameter = event_link != null ?
                new ObjectParameter("event_link", event_link) :
                new ObjectParameter("event_link", typeof(string));
    
            var event_expir_dateParameter = event_expir_date.HasValue ?
                new ObjectParameter("event_expir_date", event_expir_date) :
                new ObjectParameter("event_expir_date", typeof(System.DateTime));
    
            var created_atParameter = created_at.HasValue ?
                new ObjectParameter("created_at", created_at) :
                new ObjectParameter("created_at", typeof(System.DateTime));
    
            var created_byParameter = created_by != null ?
                new ObjectParameter("created_by", created_by) :
                new ObjectParameter("created_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_upcoming_event", event_guidParameter, event_date_timeParameter, event_titleParameter, event_detailsParameter, campusParameter, event_linkParameter, event_expir_dateParameter, created_atParameter, created_byParameter);
        }
    
        public virtual int update_upcoming_event(Nullable<int> event_id, Nullable<System.Guid> event_guid, Nullable<System.DateTime> event_date_time, string event_title, string event_details, string campus, string event_link, Nullable<System.DateTime> event_expir_date, Nullable<System.DateTime> created_at, string created_by, Nullable<System.DateTime> updated_at, string updated_by)
        {
            var event_idParameter = event_id.HasValue ?
                new ObjectParameter("event_id", event_id) :
                new ObjectParameter("event_id", typeof(int));
    
            var event_guidParameter = event_guid.HasValue ?
                new ObjectParameter("event_guid", event_guid) :
                new ObjectParameter("event_guid", typeof(System.Guid));
    
            var event_date_timeParameter = event_date_time.HasValue ?
                new ObjectParameter("event_date_time", event_date_time) :
                new ObjectParameter("event_date_time", typeof(System.DateTime));
    
            var event_titleParameter = event_title != null ?
                new ObjectParameter("event_title", event_title) :
                new ObjectParameter("event_title", typeof(string));
    
            var event_detailsParameter = event_details != null ?
                new ObjectParameter("event_details", event_details) :
                new ObjectParameter("event_details", typeof(string));
    
            var campusParameter = campus != null ?
                new ObjectParameter("campus", campus) :
                new ObjectParameter("campus", typeof(string));
    
            var event_linkParameter = event_link != null ?
                new ObjectParameter("event_link", event_link) :
                new ObjectParameter("event_link", typeof(string));
    
            var event_expir_dateParameter = event_expir_date.HasValue ?
                new ObjectParameter("event_expir_date", event_expir_date) :
                new ObjectParameter("event_expir_date", typeof(System.DateTime));
    
            var created_atParameter = created_at.HasValue ?
                new ObjectParameter("created_at", created_at) :
                new ObjectParameter("created_at", typeof(System.DateTime));
    
            var created_byParameter = created_by != null ?
                new ObjectParameter("created_by", created_by) :
                new ObjectParameter("created_by", typeof(string));
    
            var updated_atParameter = updated_at.HasValue ?
                new ObjectParameter("updated_at", updated_at) :
                new ObjectParameter("updated_at", typeof(System.DateTime));
    
            var updated_byParameter = updated_by != null ?
                new ObjectParameter("updated_by", updated_by) :
                new ObjectParameter("updated_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_upcoming_event", event_idParameter, event_guidParameter, event_date_timeParameter, event_titleParameter, event_detailsParameter, campusParameter, event_linkParameter, event_expir_dateParameter, created_atParameter, created_byParameter, updated_atParameter, updated_byParameter);
        }
    
        public virtual int insert_news(Nullable<System.Guid> news_guid, string news_title, Nullable<System.DateTime> news_date, string news_details, string campus, string news_image, string news_link, Nullable<System.DateTime> news_expir_date, Nullable<System.DateTime> created_at, string created_by)
        {
            var news_guidParameter = news_guid.HasValue ?
                new ObjectParameter("news_guid", news_guid) :
                new ObjectParameter("news_guid", typeof(System.Guid));
    
            var news_titleParameter = news_title != null ?
                new ObjectParameter("news_title", news_title) :
                new ObjectParameter("news_title", typeof(string));
    
            var news_dateParameter = news_date.HasValue ?
                new ObjectParameter("news_date", news_date) :
                new ObjectParameter("news_date", typeof(System.DateTime));
    
            var news_detailsParameter = news_details != null ?
                new ObjectParameter("news_details", news_details) :
                new ObjectParameter("news_details", typeof(string));
    
            var campusParameter = campus != null ?
                new ObjectParameter("campus", campus) :
                new ObjectParameter("campus", typeof(string));
    
            var news_imageParameter = news_image != null ?
                new ObjectParameter("news_image", news_image) :
                new ObjectParameter("news_image", typeof(string));
    
            var news_linkParameter = news_link != null ?
                new ObjectParameter("news_link", news_link) :
                new ObjectParameter("news_link", typeof(string));
    
            var news_expir_dateParameter = news_expir_date.HasValue ?
                new ObjectParameter("news_expir_date", news_expir_date) :
                new ObjectParameter("news_expir_date", typeof(System.DateTime));
    
            var created_atParameter = created_at.HasValue ?
                new ObjectParameter("created_at", created_at) :
                new ObjectParameter("created_at", typeof(System.DateTime));
    
            var created_byParameter = created_by != null ?
                new ObjectParameter("created_by", created_by) :
                new ObjectParameter("created_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("insert_news", news_guidParameter, news_titleParameter, news_dateParameter, news_detailsParameter, campusParameter, news_imageParameter, news_linkParameter, news_expir_dateParameter, created_atParameter, created_byParameter);
        }
    
        public virtual int update_news(Nullable<int> news_id, string news_title, Nullable<System.DateTime> news_date, string news_details, string campus, string news_image, string news_link, Nullable<System.DateTime> news_expir_date, Nullable<System.DateTime> created_at, string created_by, Nullable<System.DateTime> updated_at, string updated_by)
        {
            var news_idParameter = news_id.HasValue ?
                new ObjectParameter("news_id", news_id) :
                new ObjectParameter("news_id", typeof(int));
    
            var news_titleParameter = news_title != null ?
                new ObjectParameter("news_title", news_title) :
                new ObjectParameter("news_title", typeof(string));
    
            var news_dateParameter = news_date.HasValue ?
                new ObjectParameter("news_date", news_date) :
                new ObjectParameter("news_date", typeof(System.DateTime));
    
            var news_detailsParameter = news_details != null ?
                new ObjectParameter("news_details", news_details) :
                new ObjectParameter("news_details", typeof(string));
    
            var campusParameter = campus != null ?
                new ObjectParameter("campus", campus) :
                new ObjectParameter("campus", typeof(string));
    
            var news_imageParameter = news_image != null ?
                new ObjectParameter("news_image", news_image) :
                new ObjectParameter("news_image", typeof(string));
    
            var news_linkParameter = news_link != null ?
                new ObjectParameter("news_link", news_link) :
                new ObjectParameter("news_link", typeof(string));
    
            var news_expir_dateParameter = news_expir_date.HasValue ?
                new ObjectParameter("news_expir_date", news_expir_date) :
                new ObjectParameter("news_expir_date", typeof(System.DateTime));
    
            var created_atParameter = created_at.HasValue ?
                new ObjectParameter("created_at", created_at) :
                new ObjectParameter("created_at", typeof(System.DateTime));
    
            var created_byParameter = created_by != null ?
                new ObjectParameter("created_by", created_by) :
                new ObjectParameter("created_by", typeof(string));
    
            var updated_atParameter = updated_at.HasValue ?
                new ObjectParameter("updated_at", updated_at) :
                new ObjectParameter("updated_at", typeof(System.DateTime));
    
            var updated_byParameter = updated_by != null ?
                new ObjectParameter("updated_by", updated_by) :
                new ObjectParameter("updated_by", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("update_news", news_idParameter, news_titleParameter, news_dateParameter, news_detailsParameter, campusParameter, news_imageParameter, news_linkParameter, news_expir_dateParameter, created_atParameter, created_byParameter, updated_atParameter, updated_byParameter);
        }
    }
}
