//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class job_post
    {
        [DisplayName("Job Post ID")]
        public int job_post_id { get; set; }
        [DisplayName("Campus")]
        [Required]
        public string campus { get; set; }
        [DisplayName("Title")]
        [Required]
        public string title { get; set; }
        [DisplayName("Category")]
        [Required]
        public string category { get; set; }
        [DisplayName("Post Type")]
        [Required]
        public string post_type { get; set; }
        [DisplayName("Location")]
        [Required]
        public string location { get; set; }
        [DisplayName("Description")]
        [Required]
        public string description { get; set; }
        [DisplayName("Salary")]
        [Required]
        public string salary { get; set; }
        [DisplayName("Tags")]
        [Required]
        public string tags { get; set; }
        [DisplayName("Image")]
        public string image_path { get; set; }
        [DisplayName("Created At")]
        public Nullable<System.DateTime> created_at { get; set; }
        [DisplayName("Created By")]
        public string created_by { get; set; }
        [DisplayName("Updated At")]
        public Nullable<System.DateTime> updated_at { get; set; }
        [DisplayName("Updated By")]
        public string updated_by { get; set; }
    }
}
