//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public member()
        {
            this.member_candidate = new HashSet<member_candidate>();
        }

        [Required(ErrorMessage = "This field is required", AllowEmptyStrings = false)]
        [MaxLength(30, ErrorMessage = "Name must contain maximum 30 characters")]
        [MinLength(3, ErrorMessage = "Name must contain minimum 3 characters")]
        [DisplayName("Name")]
        public string name { get; set; }


        [Required(ErrorMessage = "This field is required", AllowEmptyStrings = false)]
        [DataType(DataType.EmailAddress, ErrorMessage = "Invalid Email Address")]
        [MaxLength(50, ErrorMessage = "Name must contain maximum 30 characters")]
        [DisplayName("Email")]
        public string email { get; set; }


        [DisplayName("Member Guid")]
        public System.Guid guid { get; set; }

        [Required(ErrorMessage = "This field is required", AllowEmptyStrings = false)]
        [DataType(DataType.PhoneNumber, ErrorMessage = "Invalid Mobile Number")]
        [DisplayName("Mobile Number")]
        public string mobile_no { get; set; }


        [DisplayName("IP Address")]
        [ScaffoldColumn(false)]
        public string ip_address { get; set; }

        [DisplayName("Headers")]
        [ScaffoldColumn(false)]
        public string headers { get; set; }


        [DisplayName("Creatd At")]
        public Nullable<System.DateTime> created_at { get; set; }


        [DisplayName("Creatd By")]
        public string created_by { get; set; }


        [DisplayName("Updated At")]
        public Nullable<System.DateTime> updated_at { get; set; }


        [DisplayName("Updated By")]
        public string updated_by { get; set; }


        [DisplayName("Member Id")]
        public int member_id { get; set; }


        [DisplayName("Already Voted")]
        public Nullable<bool> already_voted { get; set; }

        [Required(ErrorMessage = "This field is required", AllowEmptyStrings = false)]
        [DataType(DataType.Password)]
        [MaxLength(30, ErrorMessage = "Password must contain maximum 30 characters")]
        [MinLength(5, ErrorMessage = "Password must contain minimum 3 characters")]
        [DisplayName("Password")]
        public string password { get; set; }

        [Required(ErrorMessage = "This field is required", AllowEmptyStrings = false)]
        [DataType(DataType.Password)]
        [MaxLength(30, ErrorMessage = "Confirm Password must contain maximum 30 characters")]
        [MinLength(5, ErrorMessage = "Confirm Password must contain minimum 3 characters")]
        [Compare("password", ErrorMessage = "Password and Confirm Password do not match")]
        [DisplayName("Confirm Password")]
        public string confirm_password { get; set; }

        [MaxLength(30, ErrorMessage = "Registration Number must contain maximum 30 characters")]
        [MinLength(5, ErrorMessage = "Registration Number must contain minimum 3 characters")]
        [DisplayName("Registration Number")]
        public string registration_no { get; set; }

        [Required(ErrorMessage = "This field is required", AllowEmptyStrings = false)]
        [DataType(DataType.DateTime)]
        [DisplayName("Degree Completion Date")]
        public Nullable<System.DateTime> degree_completion_date { get; set; }

        [Required(ErrorMessage = "This field is required", AllowEmptyStrings = false)]
        [MaxLength(50, ErrorMessage = "Campus must contain maximum 50 characters")]
        [MinLength(4, ErrorMessage = "Campus must contain minimum 3 characters")]
        [DisplayName("Campus")]
        public string campus { get; set; }

        [Required(ErrorMessage = "This field is required", AllowEmptyStrings = false)]
        [MaxLength(50, ErrorMessage = "Program Studied must contain maximum 50 characters")]
        [MinLength(3, ErrorMessage = "Program Studied Number must contain minimum 3 characters")]
        [DisplayName("Program Studied")]
        public string program_studied { get; set; }

        [Required(ErrorMessage = "This field is required", AllowEmptyStrings = false)]
        [MaxLength(50, ErrorMessage = "Org/Company Working In must contain maximum 50 characters")]
        [MinLength(3, ErrorMessage = "Org/Company Working In must contain minimum 3 characters")]
        [DisplayName("Org/Company Working In")]
        public string org_comp_working_in { get; set; }

        [Required(ErrorMessage = "This field is required", AllowEmptyStrings = false)]
        [MaxLength(50, ErrorMessage = "Designation must contain maximum 50 characters")]
        [MinLength(3, ErrorMessage = "Designation must contain minimum 3 characters")]
        [DisplayName("Designation")]
        public string designation { get; set; }


        [DisplayName("Validation Status")]
        public int validation_status { get; set; }

        [DisplayName("Category Studied")]
        [Required(ErrorMessage = "This field is required", AllowEmptyStrings = false)]
        [MaxLength(50, ErrorMessage = "Category must contain maximum 50 characters")]
        [MinLength(2, ErrorMessage = "Category must contain minimum 2 characters")]
        public string category_studied { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<member_candidate> member_candidate { get; set; }
        public virtual validation_status validation_status1 { get; set; }
    }
}
