//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class news
    {
        [DisplayName("News ID")]
        public int news_id { get; set; }

        [DisplayName("News GUID")]
        public Nullable<System.Guid> news_guid { get; set; }

        [Required]
        [DisplayName("News Title")]
        public string news_title { get; set; }

        [Required]
        [DisplayName("News Date")]
        public Nullable<System.DateTime> news_date { get; set; }

        [Required]
        [DisplayName("News Details")]
        public string news_details { get; set; }

        [Required]
        [DisplayName("Campus")]
        public string campus { get; set; }

        [DisplayName("News Image")]
        public string news_image { get; set; }

        [DisplayName("News Link")]
        public string news_link { get; set; }

        [Required]
        [DisplayName("News Expir Date")]
        public Nullable<System.DateTime> news_expir_date { get; set; }

        [DisplayName("Created At")]
        public Nullable<System.DateTime> created_at { get; set; }

        [DisplayName("Created By")]
        public string created_by { get; set; }

        [DisplayName("Updated At")]
        public Nullable<System.DateTime> updated_at { get; set; }

        [DisplayName("Updated By")]
        public string updated_by { get; set; }
    }
}
