//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class upcoming_event
    {
        [DisplayName("Event ID")]
        public int event_id { get; set; }

        [DisplayName("Event GUID")]
        public System.Guid event_guid { get; set; }

        [DisplayName("Event Date")]
        [Required]
        public Nullable<System.DateTime> event_date_time { get; set; }

        [DisplayName("Event Titile")]
        [Required]
        public string event_title { get; set; }

        [DisplayName("Event Details")]
        [Required]
        public string event_details { get; set; }

        [DisplayName("Campus")]
        [Required]
        public string campus { get; set; }

        [DisplayName("Event Link")]
        [Required]
        public string event_link { get; set; }

        [DisplayName("Event Expir Date")]
        [Required]
        public Nullable<System.DateTime> event_expir_date { get; set; }

        [DisplayName("Created At")]
        public Nullable<System.DateTime> created_at { get; set; }

        [DisplayName("Created By")]
        public string created_by { get; set; }

        [DisplayName("Updated At")]
        public Nullable<System.DateTime> updated_at { get; set; }

        [DisplayName("Updated By")]
        public string updated_by { get; set; }
    }
}
